name: weekly download of NCEI Lebanon data

#when it should run
on:
  schedule:
    - cron: "0 5 * * 1" #run every Monday at 5 UTC / midnight EST
  push:
    branches: main #run when there's a push on the main branch

#create jobs    
jobs:
  ncei-download: 
    runs-on: windows-latest
    steps: 
    # load repo
    - uses: actions/checkout@v2
    # setup r
    - uses: r-lib/actions/setup-r@v2
    # install packages
    - name: Install packages
      run: |
        install.packages(c('tidyverse', 'rnoaa'), dependencies = T)
      shell: Rscript {0}
    # run script
    - name: download and concatenate NCEI data
      run: Rscript download_compile.R
    #commit files to GH  
    - name: Commit files
      run: |
        git config --local user.name actions-user
        git config --local user.email "actions@github.com"
        git add NCEI_Lebanon_hourly_*
        git commit -am "gh action NCEI download $(date)"
        git push origin main



